on:
  push:
jobs:
  hello world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello word, from my home"
      - name: "checkout"
        uses: actions/checkout@ed68ef82c095e0d48ec87eccea555d944a631a4c #Version 46.0.5

      - name: "print files"
        run: |
          ls 
          pwd
          
