name: CloudCamp CI
on:
  push:
  workflow_dispatch:
    inputs:
      should_deploy:
        type: boolean
      text_field:
        type: String
        required: true
        default: test


jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"      
        #Clone teh repository
      - name: "checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #version 4.2.2
        #recomendaicon siempre poner el sha, lo obtienes en el ultimo release y mirar el sha en la url
        
      - name: "print files"
        run: | 
          ls
          pwd
    
      - uses: hashicorp/setup-terraform@v3
      - run: terraform version

  #generar una dependencia del step hello_world
  job-depends:
    if: ${{  inputs.should_deploy  }}
    runs-on: ubuntu-latest
    needs: [hello_world]
    steps:
      - run: echo "${{  github.actor  }}"

  Terraform:
    name: Terraform CI
    runs-on: ubuntu-latest

    env:
      #TERNER EN CUENTA NOMRES EN EL REPOSITORIO
      AWS_ACCESS_KEY_ID: ${{  secrets.AWS_ACCESS_KEY_ID  }}
      AWS_SECRET_ACCESS_KEY: ${{  secrets.AWS_SECRET_ACCESS_KEY  }}

    steps:
      - name: "checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #version 4.2.2
      
      - uses: hashicorp/setup-terraform@v3

      - name: "terraform init"
        run:  terraform init

      - name: "terraform plan"
        run: terraform plan
