name: cloudCamp CI
on:
  push:
jobs:
  hello world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello word, from my home"
      #- name: "checkout"
      #  uses: actions/checkout@ed68ef82c095e0d48ec87eccea555d944a631a4c #Version 46.0.5

#      - name: "print files"
#        run: |
#          ls 
#          pwd
#
#      - uses: hashicorp/setup-terraform@v3
#      - run: terraform version
#
#  job-depends:
#    runs-on: ubuntu-latest
#    needs: [hellow_world]
#    steps:
#      - run: echo "${{  github.actor  }}" 
#
#  terraform:
#    name: Terraform CI
#    runs-on: ubuntu-latest
#    
#    env:
#      AWS_ACCES_KEY_ID:  "${{  secrets.AWS_ACCES_KEY_ID  }}" 
#      AWS_SECRET_ACCES_KEY: "${{  secrets.AWS_SECRET_ACCES_KEY  }}" 
#
#    steps:
#      - name: "checkout"
#        uses: actions/checkout@ed68ef82c095e0d48ec87eccea555d944a631a4c #Version 46.0.5
#      - uses: hashicorp/setup-terraform@v3
#      
#      - name: "Terraform'init"
#        run: terraform init
#
#      - name: "terraform plan"
#        run: terraform plan